packages:
  - 'packages/*'
  - 'frontend'

minimumReleaseAge: 4320

pmOnFail: error

allowBuilds:
  '@reown/appkit': false
  '@scarf/scarf': false
  '@tailwindcss/oxide': false
  bufferutil: false
  kubo: true
  unrs-resolver: false
  utf-8-validate: false
